export const COLOR = {
    WHITE_CELL: 'white',
    GAME_CELLS: 'lightgray',
    SELECTED_ITEM: 'green',
    ALERT_HANDLER: 'white',
    ALERT_TITLE: 'black',
    TEXT: 'black',
    CELL_BORDER: '#8bb8ca',
    TOUCHABLE_OPACITY_BUTTON: 'rgba(0, 0, 0, 0.3)',
    BLACK: '#5f5f5f',
    WHITE: 'white',
    YELLOW: 'yellow',
    BACK_GROUND_COLOR: '#272B33',
    AJORY: '#C93527',
};